---
# Converge playbook for Molecule testing
# This is the main deployment playbook for the Kafka cluster

- name: Apply common role to all nodes
  hosts: all:!kafkaui
  gather_facts: true
  roles:
    - role: hermanwong.kafka.common

- name: Install Java on ZooKeeper and Kafka nodes
  hosts: zookeeper:kafka
  gather_facts: true
  roles:
    - role: hermanwong.kafka.java

- name: Deploy ZooKeeper cluster
  hosts: zookeeper
  gather_facts: true
  pre_tasks:
    - name: Set ZooKeeper myid dynamically
      ansible.builtin.set_fact:
        zookeeper_myid: "{{ groups['zookeeper'].index(inventory_hostname) + 1 }}"
  roles:
    - role: hermanwong.kafka.zookeeper

- name: Deploy Kafka cluster
  hosts: kafka
  gather_facts: true
  pre_tasks:
    - name: Set Kafka broker ID dynamically
      ansible.builtin.set_fact:
        kafka_broker_id: "{{ groups['kafka'].index(inventory_hostname) + 1 }}"
  roles:
    - role: hermanwong.kafka.kafka
