---
# Converge playbook for Molecule testing
# This is the main deployment playbook for the Kafka cluster

- name: Apply common role to all nodes
  hosts: all
  gather_facts: true
  roles:
    - role: common

- name: Install Java on ZooKeeper and Kafka nodes
  hosts: zookeeper:kafka
  gather_facts: true
  roles:
    - role: java

- name: Deploy ZooKeeper cluster
  hosts: zookeeper
  gather_facts: true
  roles:
    - role: zookeeper

- name: Deploy Kafka cluster
  hosts: kafka
  gather_facts: true
  roles:
    - role: kafka
