---
# Molecule configuration for full Kafka cluster testing
# This scenario deploys: 1 Root CA + 3 ZooKeeper + 3 Kafka nodes

dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

driver:
  name: docker

platforms:
  # Root CA node
  - name: rootca1
    image: kafka-ansible/rocky9-systemd
    dockerfile: ../../../containers/rocky/9/Dockerfile
    pre_build_image: false
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /usr/sbin/init
    groups:
      - rootca

  # ZooKeeper nodes
  - name: zk1
    image: kafka-ansible/rocky9-systemd
    dockerfile: ../../../containers/rocky/9/Dockerfile
    pre_build_image: false
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /usr/sbin/init
    groups:
      - zookeeper

  - name: zk2
    image: kafka-ansible/rocky9-systemd
    dockerfile: ../../../containers/rocky/9/Dockerfile
    pre_build_image: false
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /usr/sbin/init
    groups:
      - zookeeper

  - name: zk3
    image: kafka-ansible/rocky9-systemd
    dockerfile: ../../../containers/rocky/9/Dockerfile
    pre_build_image: false
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /usr/sbin/init
    groups:
      - zookeeper

  # Kafka broker nodes
  - name: kafka1
    image: kafka-ansible/rocky9-systemd
    dockerfile: ../../../containers/rocky/9/Dockerfile
    pre_build_image: false
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /usr/sbin/init
    groups:
      - kafka

  - name: kafka2
    image: kafka-ansible/rocky9-systemd
    dockerfile: ../../../containers/rocky/9/Dockerfile
    pre_build_image: false
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /usr/sbin/init
    groups:
      - kafka

  - name: kafka3
    image: kafka-ansible/rocky9-systemd
    dockerfile: ../../../containers/rocky/9/Dockerfile
    pre_build_image: false
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /usr/sbin/init
    groups:
      - kafka

provisioner:
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: "true"
    ANSIBLE_VERBOSITY: "1"
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
      gathering: smart
      stdout_callback: yaml
    ssh_connection:
      pipelining: true
  inventory:
    group_vars:
      all:
        ansible_user: root
        ansible_python_interpreter: /usr/bin/python3
      zookeeper:
        zookeeper_myid: "{{ groups['zookeeper'].index(inventory_hostname) + 1 }}"
        zookeeper_cluster_nodes: "{{ groups['zookeeper'] }}"
      kafka:
        kafka_broker_id: "{{ groups['kafka'].index(inventory_hostname) + 1 }}"
        kafka_zookeeper_connect: "{{ groups['zookeeper'] | map('regex_replace', '^(.*)$', '\\1:2181') | join(',') }}"

verifier:
  name: ansible

scenario:
  create_sequence:
    - create
    - prepare
  converge_sequence:
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
